version: '3'
services:
  convert-fbx-binary:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_binary.py resources/cube.obj resources/cube_binary.fbx
