version: '3'
services:
  convert-fbx-binary:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_binary.py resources/cube.obj resources/cube_binary.fbx

  convert-fbx-ascii:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./convert_fbx:/src/convert_fbx
    working_dir: /src
    command: python convert_fbx/fbx_ascii.py resources/cube_binary.fbx resources/cube_ascii.fbx

  list-format:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./show:/src/show
    working_dir: /src
    command: python show/list_format.py

  show-attribute:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./show:/src/show
    working_dir: /src
    command: python show/show_attribute.py resources/cube_binary.fbx

  generate-camera-anim:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./generate_fbx:/src/generate_fbx
    working_dir: /src
    command: python generate_fbx/camera_anim.py resources/camera_anim_ascii.fbx

  large-cube:
    image: lerignoux/python-fbx:latest
    volumes:
      - ./resources:/src/resources
      - ./generate_fbx:/src/generate_fbx
    working_dir: /src
    command: python generate_fbx/large_cube.py resources/large_cube.fbx
